import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useAuth } from '@/context/AuthContext'



export default function Home() {

  const { currentUser } = useAuth()


  return (
    <>
      <Head>
        <title>NextJS Authentication</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {/* if currentUser exists as a global state, only then render welcome message, if not, render login/register message */}

        { 
          currentUser
          ?
          (
            <h1>Welcome!</h1>
          )
          :
          (
            <h1>Register or Log In</h1>
          ) 
        }

      </div>
    </>
  )
}
