import { useState } from 'react';
import Button from 'react-bootstrap/Button';
import FloatingLabel from 'react-bootstrap/FloatingLabel';
import Form from 'react-bootstrap/Form';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { useAuth } from '@/context/AuthContext';

export default function LoginPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  // need this to change url
  const router = useRouter();

  const { login } = useAuth()

  const submitHandler = async () => {
    // client side validation
    if(!email || !password) return

    return login(email, password)

  }
  


  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>

        <Form
        onSubmit={submitHandler}
        style={{ width: "80%", margin: "2rem auto"}}
        >

          <h1>Login</h1>

          <FloatingLabel
          controlId="floatingInput"
          label="Email address"
          className="my-4"
          >
            <Form.Control
            type="text"
            placeholder="name@example.com"
            onChange={e => setEmail(e.target.value)}
            />
          </FloatingLabel>

          <FloatingLabel
          controlId="floatingPassword"
          label="Password"
          className="my-4"
          >
            <Form.Control
            type="password"
            placeholder="Password"
            onChange={e => setPassword(e.target.value)}
            />
          </FloatingLabel>

          <Button
          type="submit"
          variant='primary'
          >
            Log In
          </Button>

        </Form>

      </div>
    </>
  )
}
